namespace XiControl.Localization;

public enum Lang { Ru = 0, En = 1, Zh = 2 }

/// <summary>Простая локализация RU/EN/ZH. Ключ → [ru, en, zh].</summary>
public static class Loc
{
    public static Lang Current = Lang.Ru;

    private static readonly Dictionary<string, string[]> S = new()
    {
        ["app.name"]        = ["Xi Control", "Xi Control", "Xi Control"],
        ["menu.charge"]     = ["Беречь батарею (80%)", "Battery care (80%)", "电池保护 (80%)"],
        ["menu.travel"]     = ["Зарядить «в дорогу» (100%)", "Travel charge (100%)", "出行充电 (100%)"],
        ["menu.travel.sound"] = ["Звук готовности «в дорогу»", "Travel ready sound", "出行完成提示音"],
        ["menu.perf"]       = ["Режим производительности", "Performance mode", "性能模式"],
        ["mode.eco"]        = ["Эко", "Eco", "节能"],
        ["mode.quiet"]      = ["Тихий", "Quiet", "静音"],
        ["mode.turbo"]      = ["Турбо", "Turbo", "高性能"],
        ["mode.full"]       = ["Полная мощность", "Full speed", "全速"],
        ["mode.auto"]       = ["Авто", "Auto", "智能"],
        ["menu.settings"]   = ["Настройки", "Settings", "设置"],
        ["menu.show.eco"]   = ["Показывать «Эко»", "Show Eco mode", "显示节能模式"],
        ["menu.show.full"]  = ["Показывать «Полную мощность»", "Show Full speed mode", "显示全速模式"],
        ["menu.startmode"]         = ["Режим при старте", "Startup mode", "启动模式"],
        ["menu.startmode.restore"] = ["Восстанавливать последний", "Restore last used", "恢复上次使用"],
        ["menu.startmode.pin"]     = ["Закрепить текущий режим", "Pin current mode", "锁定当前模式"],
        ["menu.startmode.power"]   = ["Профили питания", "Power profiles", "电源配置"],
        ["menu.profile.ac"]        = ["При зарядке", "When charging", "接通电源时"],
        ["menu.profile.battery"]   = ["От батареи", "On battery", "使用电池时"],
        ["menu.profile.nochange"]  = ["Не менять", "Don’t change", "不更改"],
        ["menu.profile.brightness"]= ["Запоминать яркость", "Remember brightness", "记住亮度"],
        ["menu.mi.perf"]    = ["Клик Mi — производительность", "Mi click: performance", "Mi 单击切换性能"],
        ["menu.mi.double"]  = ["Двойной клик Mi", "Mi double click", "Mi 双击"],
        ["menu.key.charge"] = ["Клавиша настроек — заряд", "Settings key: charge", "设置键切换充电"],
        ["menu.owl"]        = ["Режим совы (не спать)", "Owl mode (keep awake)", "猫头鹰模式（保持唤醒）"],
        ["menu.hz"]         = ["Авто-герцовка ({0}/{1} Гц)", "Auto refresh rate ({0}/{1} Hz)", "自动刷新率（{0}/{1} Hz）"],
        ["menu.owl.enable"] = ["Включить режим совы", "Enable owl mode", "启用猫头鹰模式"],
        ["menu.language"]   = ["Язык", "Language", "语言"],
        ["menu.autostart"]  = ["Запускать с Windows", "Start with Windows", "开机自启动"],
        ["menu.exit"]       = ["Выход", "Exit", "退出"],

        // --- Окно настроек ---
        ["settings.title"]        = ["Настройки XiControl", "XiControl Settings", "XiControl 设置"],
        ["settings.tab.general"]  = ["Общие", "General", "常规"],
        ["settings.tab.battery"]  = ["Батарея", "Battery", "电池"],
        ["settings.tab.display"]  = ["Экран", "Display", "屏幕"],
        ["settings.tab.perf"]     = ["Производительность", "Performance", "性能"],
        ["settings.tab.keys"]     = ["Клавиши", "Keys", "按键"],
        ["settings.tab.about"]    = ["О программе", "About", "关于"],

        ["settings.general.sub"]  = ["Язык, запуск с Windows и общие удобства.", "Language, startup and general conveniences.", "语言、开机启动与通用便捷设置。"],
        ["settings.language"]     = ["Язык", "Language", "语言"],
        ["settings.language.desc"]= ["Язык меню, панели и всплывашек.", "Language of the menu, panel and pop-ups.", "菜单、面板和提示的语言。"],
        ["settings.autostart"]    = ["Запускать при входе в Windows", "Start with Windows", "开机自启动"],
        ["settings.autostart.desc"]= ["Через Планировщик заданий, без запроса UAC.", "Via Task Scheduler, without a UAC prompt.", "通过任务计划程序，无需 UAC 提示。"],
        ["settings.general.comfort"]= ["Удобства", "Comfort", "便捷功能"],
        ["settings.brightness.desc"]= ["Отдельно для сети и батареи; без «Профилей».", "Separately for AC and battery; no Power profiles.", "分别用于电源和电池，无需电源配置。"],

        ["settings.battery.sub"]  = ["Режим «В дорогу» и звук готовности заряда.", "Travel mode and the charge-ready sound.", "出行模式与充电完成提示音。"],
        ["settings.battery.note"] = ["Порог «Беречь батарею» (≈80%) зашит в прошивку и одинаков для модели — произвольный процент недоступен. Сам тумблер 80/100 живёт в трее и панели как быстрое действие.", "The battery-care threshold (~80%) is fixed in firmware for this model — an arbitrary percent isn’t possible. The 80/100 toggle itself lives in the tray and panel as a quick action.", "“电池保护”阈值（约 80%）由固件固定，无法自定义百分比。80/100 开关作为快捷操作位于托盘和面板中。"],
        ["settings.battery.travel"]= ["Режим «В дорогу»", "Travel mode", "出行模式"],
        ["settings.travel.sound"] = ["Звук готовности", "Ready sound", "完成提示音"],
        ["settings.travel.sound.desc"]= ["Джингл, когда батарея дозарядилась до 100%.", "A jingle when the battery reaches 100%.", "电池充至 100% 时播放提示音。"],
        ["settings.travel.file"]  = ["Свой звуковой файл", "Custom sound file", "自定义音频文件"],
        ["settings.travel.file.desc"]= ["WAV/PCM. Пусто — встроенный джингл.", "WAV/PCM. Empty — built-in jingle.", "WAV/PCM。留空则使用内置提示音。"],
        ["settings.browse"]       = ["Обзор…", "Browse…", "浏览…"],

        ["settings.display.sub"]  = ["Частота обновления в зависимости от питания.", "Refresh rate depending on the power source.", "根据电源自动切换刷新率。"],
        ["settings.hz.auto"]      = ["Авто-частота по питанию", "Auto refresh rate by power", "按电源自动刷新率"],
        ["settings.hz.auto.desc"] = ["Повышенная от сети, пониженная от батареи — экономит заряд.", "Higher on AC, lower on battery — saves power.", "接通电源时更高，使用电池时更低，省电。"],
        ["settings.hz.rates"]     = ["Частоты", "Rates", "刷新率"],
        ["settings.hz.unit"]      = ["Гц", "Hz", "Hz"],
        ["settings.hz.ac"]        = ["От сети", "On AC", "接通电源"],
        ["settings.hz.ac.desc"]   = ["Если точной частоты нет — берётся ближайшая.", "If the exact rate is missing — the nearest is used.", "若无精确刷新率则取最接近值。"],
        ["settings.hz.battery"]   = ["От батареи", "On battery", "使用电池"],
        ["settings.hz.battery.desc"]= ["Обычно 60 Гц для экономии.", "Usually 60 Hz to save power.", "通常为 60 Hz 以省电。"],

        ["settings.perf.sub"]     = ["Видимость режимов и поведение при запуске системы.", "Mode visibility and startup behavior.", "模式可见性与启动行为。"],
        ["settings.perf.modes"]   = ["Видимые режимы", "Visible modes", "可见模式"],
        ["settings.show.eco"]     = ["Показывать режим «Эко»", "Show Eco mode", "显示节能模式"],
        ["settings.show.eco.desc"]= ["Скрытый энергосберегающий режим прошивки.", "The firmware’s hidden power-saving mode.", "固件隐藏的节能模式。"],
        ["settings.show.full"]    = ["Показывать «Полную мощность»", "Show Full speed mode", "显示全速模式"],
        ["settings.show.full.desc"]= ["Максимальный режим. Выкл — убирается из меню и панели.", "Maximum mode. Off — removed from menu and panel.", "最高性能模式。关闭后从菜单和面板移除。"],
        ["settings.startmode"]    = ["Режим при старте", "Startup mode", "启动模式"],
        ["settings.start.none"]   = ["Не трогать", "Leave as is", "不更改"],
        ["settings.start.none.desc"]= ["Оставлять то, что выставила прошивка.", "Keep whatever the firmware set.", "保留固件设置的模式。"],
        ["settings.start.restore"]= ["Восстанавливать последний", "Restore last used", "恢复上次使用"],
        ["settings.start.restore.desc"]= ["Запоминать выбранный режим и включать его на старте.", "Remember the chosen mode and apply it at startup.", "记住所选模式并在启动时应用。"],
        ["settings.start.pin"]    = ["Закрепить текущий", "Pin current", "锁定当前"],
        ["settings.start.pin.desc"]= ["Всегда включать один и тот же режим при загрузке.", "Always apply the same mode at boot.", "每次启动都应用同一模式。"],
        ["settings.start.profiles"]= ["Профили питания", "Power profiles", "电源配置"],
        ["settings.start.profiles.desc"]= ["Свой режим производительности при зарядке и от батареи.", "A separate performance mode on AC and battery.", "为电源和电池分别设置性能模式。"],
        ["settings.profile.ac"]   = ["Режим при зарядке", "Mode on AC", "接通电源时的模式"],
        ["settings.profile.battery"]= ["Режим от батареи", "Mode on battery", "使用电池时的模式"],
        ["settings.profile.brightness"]= ["Запоминать яркость экрана", "Remember screen brightness", "记住屏幕亮度"],
        ["settings.profile.nochange"]= ["Не менять", "Don’t change", "不更改"],

        ["settings.keys.sub"]     = ["Mi-кнопка и «мёртвые» клавиши.", "Mi button and dead keys.", "Mi 键与无效按键。"],
        ["settings.keys.mi"]      = ["Mi-кнопка", "Mi button", "Mi 键"],
        ["settings.mi.layout"]    = ["Раскладка", "Layout", "布局"],
        ["settings.mi.layout.desc"]= ["Одиночный клик; двойной — наоборот.", "Single click; double does the opposite.", "单击功能；双击相反。"],
        ["settings.mi.modes"]     = ["Клик — режимы, двойной — заряд", "Click: modes, double: charge", "单击切换模式，双击切换充电"],
        ["settings.mi.charge"]    = ["Клик — заряд, двойной — режимы", "Click: charge, double: modes", "单击切换充电，双击切换模式"],
        ["settings.mi.double"]    = ["Двойной клик", "Double click", "双击"],
        ["settings.mi.double.desc"]= ["Выкл — жест отключён, зато одиночный клик срабатывает мгновенно.", "Off — the gesture is disabled, but single click fires instantly.", "关闭后禁用手势，单击立即生效。"],
        ["settings.keys.other"]   = ["Прочие клавиши", "Other keys", "其他按键"],
        ["settings.key.settings"] = ["Клавиша «Настройки»", "“Settings” key", "“设置”键"],
        ["settings.key.settings.desc"]= ["Что делает клавиша с шестерёнкой на клавиатуре.", "What the gear key on the keyboard does.", "键盘上齿轮键的功能。"],
        ["settings.key.charge"]   = ["Заряд 80 / 100 %", "Charge 80 / 100 %", "充电 80 / 100 %"],
        ["settings.key.windows"]  = ["Открыть Параметры Windows", "Open Windows Settings", "打开 Windows 设置"],
        ["settings.ai.program"]   = ["AI-клавиша запускает", "AI key launches", "AI 键启动"],
        ["settings.ai.program.desc"]= ["Путь к программе/файлу/URL. Пусто — Copilot (Win+C).", "Path to a program/file/URL. Empty — Copilot (Win+C).", "程序/文件/URL 路径。留空则为 Copilot（Win+C）。"],
        ["settings.keys.features"]= ["Функции", "Features", "功能"],
        ["settings.owl.feature"]  = ["«Режим совы» как функция", "Owl mode feature", "猫头鹰模式功能"],
        ["settings.owl.feature.desc"]= ["Показывать сову в панели и пункт меню (не гасить экран / не спать).", "Show the owl in the panel and menu (keep screen on / no sleep).", "在面板和菜单中显示猫头鹰（保持屏幕常亮/不休眠）。"],

        ["settings.about.sub"]    = ["Driver-free трей-утилита для ноутбуков Xiaomi / Redmi.", "Driver-free tray utility for Xiaomi / Redmi laptops.", "适用于 Xiaomi / Redmi 笔记本的免驱托盘工具。"],
        ["settings.version"]      = ["Версия", "Version", "版本"],
        ["settings.about.license"]= ["Лицензия", "License", "许可证"],
        ["settings.about.updates"]= ["Проверить обновления", "Check for updates", "检查更新"],
        ["settings.about.model"]  = ["Модель", "Model", "型号"],
        ["settings.about.iface"]  = ["Интерфейс прошивки", "Firmware interface", "固件接口"],
        ["settings.about.config"] = ["Конфигурация", "Configuration", "配置文件"],
        ["settings.about.log"]    = ["Журнал", "Log", "日志"],
        ["settings.about.note"]   = ["Без kernel-драйверов, WinRing0 и прямого доступа к EC. Всё управление — через штатный WMI-интерфейс прошивки и Win32.", "No kernel drivers, WinRing0 or direct EC access. Everything goes through the firmware’s WMI interface and Win32.", "无内核驱动、无 WinRing0、不直接访问 EC。全部通过固件 WMI 接口与 Win32 实现。"],

        ["panel.title"]     = ["Быстрые настройки", "Quick settings", "快速设置"],
        ["panel.charge"]    = ["Заряд батареи", "Battery charge", "电池充电"],
        ["panel.awake"]     = ["Не спать", "Keep awake", "保持唤醒"],
        ["panel.travel"]    = ["В дорогу", "Travel", "出行"],

        ["osd.travel"]       = ["Режим «В дорогу»", "Travel mode", "出行模式"],
        ["osd.travel.sub"]   = ["Заряжаем до 100%", "Charging to 100%", "充电至 100%"],
        ["osd.travel.off"]   = ["Режим «В дорогу» выключен", "Travel mode off", "出行模式已关闭"],
        ["osd.travel.ready"] = ["Батарея заряжена — можно в дорогу!", "Battery full — ready to go!", "电池已充满，可以出发！"],

        ["menu.monitor"]    = ["Монитор", "Monitor", "监视器"],
        ["monitor.title"]   = ["Монитор", "Monitor", "监视器"],
        ["monitor.power"]   = ["Потребление", "Power draw", "功耗"],
        ["monitor.watts"]   = ["{0:0.0} Вт", "{0:0.0} W", "{0:0.0} 瓦"],
        ["monitor.na"]      = ["— от сети", "— on AC", "— 交流供电"],
        ["monitor.ram.of"]  = ["{0:0.0} / {1:0.0} ГБ", "{0:0.0} / {1:0.0} GB", "{0:0.0} / {1:0.0} GB"],
        ["monitor.watts.scale"] = ["{0:0} Вт", "{0:0} W", "{0:0} 瓦"],

        ["osd.charging"]         = ["Зарядка", "Charging", "充电中"],
        ["osd.charging.limited"] = ["Зарядка до {0}%", "Charging to {0}%", "充电至 {0}%"],
        ["osd.onbattery"]        = ["Работа от батареи", "On battery", "电池供电"],
        ["osd.level"]            = ["Заряд {0}%", "Battery {0}%", "电量 {0}%"],
        ["osd.care.on"]          = ["Беречь батарею", "Battery care", "电池保护"],
        ["osd.care.off"]         = ["Заряд до 100%", "Charge to 100%", "充电至 100%"],
        ["osd.mic.on"]           = ["Микрофон включён", "Microphone on", "麦克风已开启"],
        ["osd.mic.off"]          = ["Микрофон выключен", "Microphone off", "麦克风已静音"],
        ["osd.backlight"]        = ["Подсветка клавиатуры", "Keyboard backlight", "键盘背光"],
        ["osd.backlight.level"]  = ["{0}%", "{0}%", "{0}%"],
        ["osd.off"]              = ["Выключено", "Off", "已关闭"],
        ["osd.auto"]             = ["Авто", "Auto", "自动"],
        ["osd.hz"]               = ["{0} Гц", "{0} Hz", "{0} Hz"],
        ["osd.hz.on"]            = ["Авто-герцовка", "Auto refresh rate", "自动刷新率"],
        ["osd.hz.on.sub"]        = ["{0} Гц от сети, {1} Гц от батареи", "{0} Hz on AC, {1} Hz on battery", "交流电 {0} Hz，电池 {1} Hz"],
        ["osd.hz.off"]           = ["Авто-герцовка выключена", "Auto refresh rate off", "自动刷新率已关闭"],
        ["osd.fnlock"]           = ["Fn-Lock", "Fn-Lock", "Fn 锁定"],
        ["osd.fnlock.on"]        = ["Классические F1–F12", "Function keys F1–F12", "F1–F12 功能键"],
        ["osd.fnlock.off"]       = ["Мультимедийные клавиши", "Media keys", "多媒体按键"],

        ["err.title"]   = ["Ошибка", "Error", "错误"],
        ["err.noiface"] = [
            "Интерфейс MIFS не найден. Нужны права администратора и совместимый ноутбук Xiaomi/Redmi.",
            "MIFS interface not found. Requires administrator rights and a compatible Xiaomi/Redmi laptop.",
            "未找到 MIFS 接口。需要管理员权限和兼容的小米/红米（Redmi）笔记本电脑。"],
    };

    public static string T(string key)
        => S.TryGetValue(key, out var v) ? v[(int)Current] : key;

    public static string T(string key, params object[] args)
        => string.Format(T(key), args);
}
